### PR TITLE
EHN: Add interpretation of Apache-2.0 and set expectations

### PR DESCRIPTION
**Pull request by oesteban**
This PR addresses the discussion in nipreps/fmriprep#2325.

### CODE REVIEW

**Comment by satra** [comment]
LGTM. thanks for clarifying all of this.

**Comment by effigies** [comment]
Note from @satra:

> also while header per file could useful, not necessary: https://infra.apache.org/apply-license.html#copy-per-file

**Comment by oesteban** [comment]
As per our conversation in the roundup today, this would be the first leg of the license change. If no opposing voices comment here before next Thursday, then this will be merged on Friday. Please note that merging this document does not mean we have "passed" the relicensing of fMRIPrep (that's the other leg).
/cc @nipreps/fmriprep-contributors .

Re: missing header - current text already considers that (and recommends third-parties to add the header if it were missing, as the Apache license already recommends).

**Comment by oesteban** [comment]
Since this is not a license change itself and no voices have objected this far, I think it is pretty safe to pull it in. Thank you all for participating!

**Comment by oesteban** [comment]
The new documents are up: https://www.nipreps.org/community/licensing/

**Pull request merged**
