### PR TITLE
ENH: Add the NiPreps logo to the theme logo and favicon

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add the NiPreps logo to the theme logo and favicon.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Have not tried locally.

**Comment by jhlegarreta** [comment]
@oesteban @effigies Maybe the file https://github.com/nipreps/nipreps.github.io/blob/1e40b9d314e4be0bc0960aa33abb49c5db1aeaa7/docs/assets/nipreps_brain.png could be used to replace the organization identicon in https://github.com/nipreps?

**Comment by effigies** [comment]
Done.

**Comment by jhlegarreta** [comment]
:100: Thanks Chris.

**Pull request merged**
